[project]
name = "simple-blog"
version = "0.1.0"
requires-python = ">=3.13"
dependencies = [
    "django-bootstrap4>=24.4",
    "django>=5.1.3",
]
description = "Simple blog"
authors = ["Hexlet team <team@hexlet.io>"]
